local randomizer = {
	DrinkList = {
		'Aloe Vera Juice',
		'Apple Juice',
		'Asparagus Juice',
		'Beetroot Juice',
		'Bilimbi Juice',
		'Broccoli Juice',
		'Cabbage Juice',
		'Cactus Juice',
		'Cantaloupe Juice',
		'Carrot Juice',
		'Celery Juice',
		'Clam Juice',
		'Coconut Water',
		'Cucumber Juice',
		'Dandelion Juice',
		'Durian Juice',
		'Eggplant Juice',
		'Ginger Juice',
		'Grape Juice',
		'Grapefruit Juice',
		'Green Bean Juice',
		'Guava Juice',
		'Hemp Juice',
		'Jackfruit Juice',
		'Kaffir Lime Juice',
		'Kiwifruit Juice',
		'Lemon Juice',
		'Lychee Juice',
		'Mango Juice',
		'Melon Juice',
		'Muskmelon Juice',
		'Onion Juice',
		'Orange Juice',
		'Papaya Juice',
		'Parsley Juice',
		'Passion Fruit Juice',
		'Pineapple Juice',
		'Pizza Juice',
		'Pomegranate Juice',
		'Potato Juice',
		'POG',
		'Prune Juice',
		'Raspberry Juice',
		'Spinach Juice',
		'Strawberry Juice',
		'Sugarcane Juice',
		'Tomato Juice',
		'Tropical Juice',
		'Turmeric Juice',
		'Turnip Juice',
		'Watercress Juice',
		'Watermelon Juice',
		'Wheatgrass Juice',
		'Zucchini Juice'
	};
}

return randomizer